### ISSUE TITLE
demo selectOne 的时候运行报错

### ISSUE THREAD

**Issue by andybo19** [PaulWang92115/Paul-MyBatis#1]
你好，楼主自己手写的框架确实很好，看了以后就明白来了，mybatis的工作原理，十分感谢你的分享。我把代码本地跑了下，demo selectOne 的时候运行报错，后来Bug一下发现，在 <select id="selectByPrimaryKey" resultType="TUser">
          select *
          from t_user
          where id = #{id,jdbcType=INTEGER}
      </select>
咱们用#占位符，在prepreStatement的时候没有替换成？，所以报错。

**Comment by PaulWang92115** [comment]
谢谢你的提醒，写的比较匆忙，这块给忽略了，我修一下
